name: notify-parent-repo

on:
  push:
    branches: [ main ]

  workflow_dispatch:


jobs:
  notify-parent-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Github REST API 
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          PARENT_REPO: autifyhq/for-mobile-ci-integration-samples
          PARENT_BRANCH: main
          # curl https://api.github.com/repos/autifyhq/for-mobile-ci-integration-samples/actions/workflows/update-submodule.yml
          WORKFLOW_ID: 10802447
        run: |          
          # https://docs.github.com/en/rest/reference/actions#create-a-workflow-dispatch-event
          curl \ 
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ env.PERSONAL_ACCESS_TOKEN }}" \
            https://api.github.com/repos/${{ env.PARENT_REPO }}/actions/workflows/${{ env.WORKFLOW_ID }}/dispatches \
            -d '{"ref":"${{ env.PARENT_BRANCH }}"}'